apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: kube-logging
  labels:
    app: nginx
spec:
 # type: NodePort
  ports:
  - port: 80
 #   nodePort: 30036
  selector:
    app: nginx
---

apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: kube-logging
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.10
        ports:
        - containerPort: 80
        volumeMounts:
          - name: data
            mountPath: /var/log/nginx
      volumes:
        - name: data
          hostPath:
          # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
            path: /var/lib/filebeat-data
            type: DirectoryOrCreate