apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: myproj
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        access_log  /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log error;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
    }