apiVersion: v1
kind: Service
metadata:
  namespace: myproj
  name: nginx-service
  labels:
    app:  nginx
    service: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30080
  type: LoadBalancer