apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: myproj
  labels:
    service: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30090
    protocol: TCP
  - name: "9300"
    port: 9300
    targetPort: 9300
    protocol: TCP