apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: myproj
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        env:
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath:
                metadata.name
        - name: cluster.name
          value: escluster
        - name: discovery.seed_hosts
          value: elasticsearch-0.elasticsearch.myproj.svc.cluster.local:9300,elasticsearch-1.elasticsearch.myproj.svc.cluster.local:9300,elasticsearch-2.elasticsearch.myproj.svc.cluster.local:9300
        - name: cluster.initial_master_nodes
          value: elasticsearch-0
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        ports:
        - containerPort: 9200
          name: client
          protocol: TCP
        - containerPort: 9300
          name: nodes
          protocol: TCP