apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: myproj
spec:
  replicas: 1
  selector:
    matchLabels:
     app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:7.9.3
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-0.elasticsearch.myproj.svc.cluster.local:9200"
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch-0.elasticsearch.myproj.svc.cluster.local:9200"
        ports:
        - containerPort: 5601
          name: kibana