apiVersion: v1
kind: Service
metadata:
  namespace: myproj
  name: kibana-service
  labels:
    app: kibana
    service: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 5601
    name: kibana