apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: myproj
data:
  logstash.yml: |
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # all input will come from filebeat, no local logs
    input {
      beats {
        port => 5044
      }
    }
    filter {
      grok {
        match => { "message" => "%{IPORHOST:remote_ip} - %{DATA:user_name} \[%{HTTPDATE:access_time}\] \"%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}\" %{NUMBER:response_code} %{NUMBER:body_sent_bytes} \"%{DATA:referrer}\" \"%{DATA:agent}\"" }
        }
    }
    output {
      elasticsearch {
        hosts => [ "elasticsearch-0.elasticsearch.myproj.svc.cluster.local:9200" ]
        index => "%{[host][name]}"
      }
    }