apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
  namespace: myproj
spec:
  type: NodePort
  ports:
  - name: "9600"
    port: 9600
    targetPort: 9600
    nodePort: 30070
  - name: "5044"
    port: 5044
    targetPort: 5044
  selector:
    app: logstash